// <auto-generated />
using GeekShopping.Product.API.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.Product.API.Migrations
{
    [DbContext(typeof(MySQLContext))]
    partial class MySQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.Product.API.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("TAB_Products");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            CategoryName = "SmartPhones",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis pharetra metus. Suspendisse p",
                            ImageUrl = "",
                            Name = "Iphone 12",
                            Price = 5899.00m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "SmartPhones",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis pharetra metus. Suspendisse p",
                            ImageUrl = "",
                            Name = "Iphone XR",
                            Price = 2899.00m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "SmartPhones",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis pharetra metus. Suspendisse p",
                            ImageUrl = "",
                            Name = "Iphone 8",
                            Price = 2300.00m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "SmartPhones",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis pharetra metus. Suspendisse p",
                            ImageUrl = "",
                            Name = "Samsumg Galaxy S21",
                            Price = 3000.00m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Games",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis pharetra metus. Suspendisse p",
                            ImageUrl = "",
                            Name = "Xbox One",
                            Price = 2699.00m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Games",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis pharetra metus. Suspendisse p",
                            ImageUrl = "",
                            Name = "Playstation 5",
                            Price = 3800.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
